steps:

  # Create github release.
  - name: goreleaser/goreleaser
    entrypoint: /bin/sh
    dir: /workspace
    args: ['-c', 'git tag $TAG_NAME && goreleaser' ]
    secretEnv: ['GITHUB_TOKEN']

secrets:
  - kmsKeyName: projects/salus-220516/locations/global/keyRings/salus-tel-oracle-agent-deploy/cryptoKeys/github-token
    secretEnv:
      GITHUB_TOKEN: |
        CiQAO+30mjxK35ndt9k2N48iGdfdqH1Q7Mf6lJuUkgMNKswVfWkSUQAY+Nt/0zTHywRVKGGBMUNpZkPHrhXOW9EsXwaD6cJ0DsCPQXrSINEF4bdoCXA13zqvBEtWx3JKP9w7cTG4NK8sWYYi5aG2xDV+pTD4kfJiLQ==
